Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
  config.vm.box = "ubuntu/bionic64"
  ubuntu.vm.network "forwarded_port", guest: 80, host: 8080
  ubuntu.vm.synced_folder "/home/dell/hometask_5/Senysh", "/home/vagrant/"
  ubuntu.vm.provision "shell",
  inline:
    "docker-compose up -d"
  end 
end
